import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  consultingSidebar: [
    {
      type: "category",
      label: "Dành cho Mentor",
      description: "Hướng dẫn sử dụng cho Mentor",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "tu-van/danh-cho-mentor/huong-dan-dang-ky",
          label: "Hướng dẫn đăng ký",
        },
        {
          type: "doc",
          id: "tu-van/danh-cho-mentor/chinh-sach-cho-mentor-moi",
          label: "Chính sách cho Mentor mới",
        },
      ],
    },
    {
      type: "category",
      label: "Chương trình cộng đồng",
      description: "Giới thiệu & cách thức tham gia chương trình cộng đồng",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "tu-van/chuong-trinh-cong-dong/gioi-thieu",
          label: "Giới thiệu",
        },
        {
          type: "doc",
          id: "tu-van/chuong-trinh-cong-dong/tang-phien-tu-van-mien-phi",
          label: "Tặng phiên tư vấn miễn phí",
        },
        {
          type: "doc",
          id: "tu-van/chuong-trinh-cong-dong/quyen-gop-doanh-thu",
          label: "Quyên góp doanh thu",
        },
      ],
    },
  ],
  // seekingJobsSidebar: [{ type: "autogenerated", dirName: "tim-viec" }],
  // recruitmentSidebar: [{ type: "autogenerated", dirName: "tuyen-dung" }],
};

export default sidebars;
